version: 2.1

orbs:
  macos: circleci/macos@2.3.4

jobs:
  mac-os:
    parameters:
      version:
        default: "14.0.1"
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.m1.large.gen1
    steps:
      - run:
          name: check user log
          command: tail -f ~/Library/Logs/**/*.log
          background: true
      - run:
          name: check system log
          command: tail -f /private/var/log/**/*.log
          background: true
      - run: sysctl machdep.cpu.brand_string
      - macos/switch-ruby:
          version: "3.1.3"
      - run: gem --version && ruby --version
      - run: echo $PATH
      - run: brew install --cask android-commandlinetools
      - run: echo y | sdkmanager --licenses 
      - run: echo $PATH
      - run: gem --version && ruby --version
      - run:
          name: run
          command: gradle -q intro
          when: always
workflows:
  workflow-mac:
    jobs:
      - mac-os:
          matrix:
            parameters:
              version: ["14.1.0" ,"14.2.0", "14.3.0"]
