version: 2.1

orbs:
  macos: circleci/macos@2.3.4

jobs:
  mac-os:
    parameters:
      version:
        default: "14.0.1"
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.m1.large.gen1
    steps:
      - run: tail -f ~/Library/Logs/**/**
      - run: sysctl machdep.cpu.brand_string
      - macos/switch-ruby:
          version: "3.1.3"
      - run: gem --version && ruby --version
      - run: echo $PATH
      - run: |
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $BASH_ENV
          source $BASH_ENV

          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $BASH_ENV
          source $BASH_ENV
      - run: |
          SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip"
          mkdir -p ${ANDROID_HOME}/cmdline-tools
          wget -O /tmp/cmdline-tools.zip -t 5 "${SDK_TOOLS_URL}"
          unzip -q /tmp/cmdline-tools.zip -d ${ANDROID_HOME}/cmdline-tools
          rm /tmp/cmdline-tools.zip
          mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
      - run: |
          echo y | sdkmanager --licenses 
      - run: echo $PATH
      - run: gem --version && ruby --version
workflows:
  workflow-mac:
    jobs:
      - mac-os:
          matrix:
            parameters:
              version: ["14.1.0" ,"14.2.0", "14.3.0"]
