version: 2.1

orbs:
  macos: circleci/macos@2.3.4

jobs:
  mac-os:
    parameters:
      version:
        default: "14.0.1"
        type: string
    macos:
      xcode: << parameters.version >>
    # resource_class: macos.x86.medium.gen2
    steps:
      - run:
          name: check user log
          command: tail -f ~/Library/Logs/*
          background: true
      - run:
          name: check system log
          command: tail -f /private/var/log/**/*.log
          background: true
      - run: sysctl machdep.cpu.brand_string
      - run:
          name: Set Ruby Version
          command: rbenv install 3.0.5
      - run: gem --version && ruby --version
      - macos/switch-ruby:
          version: "3.0.5"
      - run: gem --version && ruby --version
workflows:
  workflow-mac:
    jobs:
      - mac-os:
          matrix:
            parameters:
              version: ["14.1.0" ,"14.2.0", "14.3.0"]
